name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mahir339
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t docker_practice:latest .

      - name: Tag Docker image
        run: docker tag docker_practice:latest ghcr.io/mahir339/docker_practice:latest

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/mahir339/docker_practice:latest
